//
// Created by tim on 11/24/24.
//

#ifndef COMMON_DEFINES_H
#define COMMON_DEFINES_H

// PROGRAM CONFIG
#define CENTS_IN_ONE_EURO 100
#define RANGE_OF_RANDOM_NUMS_FOR_SOLUTION 10
#define MAX_COINS 100

#endif //COMMON_DEFINES_H
